# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 24
#$ -l s_cpu=0:20:00
#$ -l mres=5.3333G,h_data=5.3333G,h_vmem=5.3333G
#$ -cwd
#$ -j y
#$ -N Grant_Test_2
#$ -o Grant_Test_2.log
#$ -M grant.tremblay@cfa.harvard.edu
#
# ----------------Modules------------------------- #
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
source ~/.dotfiles/Linux/hydra/set_eso_pipeline_environment.bash
cd /home/gtremblay/data/Data/MUSE/reduction/01_bias/
sh make_bias.sh
cd ../02_dark/
sh make_dark.sh
#
echo = `date` job $JOB_NAME done
